/**
 * @file    main.c
 * @brief   Predictive Maintenance Node — Main Entry Point
 * @target  STM32F411 Nucleo (ARM Cortex-M4)
 * @rtos    FreeRTOS v10
 *
 * Tasks:
 *  - SensorTask    : Reads IMU + Temperature at 100Hz
 *  - InferenceTask : Runs TFLite Micro model every 1s
 *  - CommsTask     : Reports anomalies via UART → ESP8266 MQTT
 *  - DisplayTask   : Updates OLED with status
 */

#include "main.h"
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "semphr.h"

#include "sensor_task.h"
#include "ml_inference.h"
#include "comms_task.h"
#include "display_task.h"

/* ── Peripheral handles (generated by CubeMX) ─────────────────────── */
I2C_HandleTypeDef  hi2c1;   /* MPU-6050 + MLX90614 + OLED */
UART_HandleTypeDef huart2;  /* ESP8266 WiFi bridge        */
TIM_HandleTypeDef  htim2;   /* 100 Hz sampling timer      */

/* ── RTOS handles ──────────────────────────────────────────────────── */
QueueHandle_t  xSensorDataQueue;   /* SensorTask  → InferenceTask  */
QueueHandle_t  xAlertQueue;        /* InferenceTask → CommsTask    */
SemaphoreHandle_t xI2CMutex;       /* Protect shared I2C bus       */

/* ── Task stack sizes (words) ──────────────────────────────────────── */
#define SENSOR_TASK_STACK    256
#define INFERENCE_TASK_STACK 1024   /* TFLite needs larger stack    */
#define COMMS_TASK_STACK     256
#define DISPLAY_TASK_STACK   256

/* ── Task priorities ───────────────────────────────────────────────── */
#define SENSOR_TASK_PRIORITY    (tskIDLE_PRIORITY + 3)
#define INFERENCE_TASK_PRIORITY (tskIDLE_PRIORITY + 2)
#define COMMS_TASK_PRIORITY     (tskIDLE_PRIORITY + 1)
#define DISPLAY_TASK_PRIORITY   (tskIDLE_PRIORITY + 1)

/* ── Queue depths ──────────────────────────────────────────────────── */
#define SENSOR_QUEUE_DEPTH  10
#define ALERT_QUEUE_DEPTH   5

/* ───────────────────────────────────────────────────────────────────── */

static void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_I2C1_Init(void);
static void MX_USART2_UART_Init(void);
static void MX_TIM2_Init(void);

int main(void)
{
    /* HAL init & system clock */
    HAL_Init();
    SystemClock_Config();

    /* Peripheral init */
    MX_GPIO_Init();
    MX_I2C1_Init();
    MX_USART2_UART_Init();
    MX_TIM2_Init();

    /* Create RTOS primitives */
    xSensorDataQueue = xQueueCreate(SENSOR_QUEUE_DEPTH, sizeof(SensorFrame_t));
    xAlertQueue      = xQueueCreate(ALERT_QUEUE_DEPTH,  sizeof(AlertMessage_t));
    xI2CMutex        = xSemaphoreCreateMutex();

    configASSERT(xSensorDataQueue != NULL);
    configASSERT(xAlertQueue      != NULL);
    configASSERT(xI2CMutex        != NULL);

    /* Create tasks */
    xTaskCreate(vSensorTask,    "Sensor",    SENSOR_TASK_STACK,    NULL, SENSOR_TASK_PRIORITY,    NULL);
    xTaskCreate(vInferenceTask, "Inference", INFERENCE_TASK_STACK, NULL, INFERENCE_TASK_PRIORITY, NULL);
    xTaskCreate(vCommsTask,     "Comms",     COMMS_TASK_STACK,     NULL, COMMS_TASK_PRIORITY,     NULL);
    xTaskCreate(vDisplayTask,   "Display",   DISPLAY_TASK_STACK,   NULL, DISPLAY_TASK_PRIORITY,   NULL);

    /* Start scheduler — never returns */
    vTaskStartScheduler();

    /* Should never reach here */
    while (1) {}
}

/* ── Clock: 100 MHz from HSI PLL (STM32F411) ──────────────────────── */
static void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
    RCC_OscInitStruct.HSIState       = RCC_HSI_ON;
    RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    RCC_OscInitStruct.PLL.PLLState   = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource  = RCC_PLLSOURCE_HSI;
    RCC_OscInitStruct.PLL.PLLM       = 8;
    RCC_OscInitStruct.PLL.PLLN       = 100;
    RCC_OscInitStruct.PLL.PLLP       = RCC_PLLP_DIV2;
    RCC_OscInitStruct.PLL.PLLQ       = 4;
    HAL_RCC_OscConfig(&RCC_OscInitStruct);

    RCC_ClkInitStruct.ClockType      = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
                                     | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider  = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;
    HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_3);
}

static void MX_GPIO_Init(void)
{
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_GPIOC_CLK_ENABLE();

    GPIO_InitTypeDef GPIO_InitStruct = {0};

    /* LED (PA5 on Nucleo) */
    GPIO_InitStruct.Pin   = GPIO_PIN_5;
    GPIO_InitStruct.Mode  = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull  = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

    /* Alert LED (PC13) */
    GPIO_InitStruct.Pin = GPIO_PIN_13;
    HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);
}

static void MX_I2C1_Init(void)
{
    hi2c1.Instance             = I2C1;
    hi2c1.Init.ClockSpeed      = 400000;  /* 400 kHz Fast Mode */
    hi2c1.Init.DutyCycle       = I2C_DUTYCYCLE_2;
    hi2c1.Init.OwnAddress1     = 0;
    hi2c1.Init.AddressingMode  = I2C_ADDRESSINGMODE_7BIT;
    hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
    hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
    hi2c1.Init.NoStretchMode   = I2C_NOSTRETCH_DISABLE;
    HAL_I2C_Init(&hi2c1);
}

static void MX_USART2_UART_Init(void)
{
    huart2.Instance          = USART2;
    huart2.Init.BaudRate     = 115200;
    huart2.Init.WordLength   = UART_WORDLENGTH_8B;
    huart2.Init.StopBits     = UART_STOPBITS_1;
    huart2.Init.Parity       = UART_PARITY_NONE;
    huart2.Init.Mode         = UART_MODE_TX_RX;
    huart2.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    huart2.Init.OverSampling = UART_OVERSAMPLING_16;
    HAL_UART_Init(&huart2);
}

static void MX_TIM2_Init(void)
{
    /* Timer used for precise 100 Hz tick notification */
    htim2.Instance               = TIM2;
    htim2.Init.Prescaler         = 9999;     /* 100MHz / 10000 = 10kHz */
    htim2.Init.CounterMode       = TIM_COUNTERMODE_UP;
    htim2.Init.Period            = 99;       /* 10kHz / 100  = 100Hz   */
    htim2.Init.ClockDivision     = TIM_CLOCKDIVISION_DIV1;
    htim2.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_ENABLE;
    HAL_TIM_Base_Init(&htim2);
}

/* FreeRTOS hook — called on stack overflow */
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    (void)xTask;
    (void)pcTaskName;
    /* Log + reset in production */
    NVIC_SystemReset();
}

/* FreeRTOS hook — called when heap is exhausted */
void vApplicationMallocFailedHook(void)
{
    NVIC_SystemReset();
}